// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuawgikivwqvkdxbqdyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1YXdnaWtpdndxdmtkeGJxZHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDkxMDMsImV4cCI6MjA2NTQyNTEwM30.F1L5BAWNFJ3YxY9y41QqMut-oRiMqBlBo72E66KA5y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);